name: publish package
on:
  release:
    types: [published]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: yarn install --frozen-lockfile
      - run: yarn run test:node
      - run: yarn run test:deno

  Release:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
